name             'biodiv'
maintainer       'Strand Life Sciences'
maintainer_email 'sravanthi@strandls.com'
license          'Apache Licese, Version 2.0'
description      'Installs/Configures biodiv'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.0'

depends          'grails-cookbook'
depends          'database'
depends          'postgresql'
depends          'application'
depends          'application_java'
depends          'nginx'
depends          'geoserver-tomcat'
depends          'biodiversity-nameparser'
depends          'postfix'
depends          'fileops'
depends          'elasticsearch'
depends          'redis'
depends          'biodiv-api'
#depends          'biodiv-ui'
depends          'naksha'
